const assert = require('assert');
const numeralize = require('../index');

describe('numeralize', () => {
    'use strict';

    const tests = [
        ['0 to 19 (minors)',
            [1,
                ['GENDER_MASCULINE',
                    ['CASE_NOMINATIVE', [true, 'один'], [false, 'один']],
                    ['CASE_GENITIVE', [true, 'одного'], [false, 'одного']],
                    ['CASE_DATIVE', [true, 'одному'], [false, 'одному']],
                    ['CASE_ACCUSATIVE', [true, 'одного'], [false, 'один']],
                    ['CASE_INSTRUMENTAL', [true, 'одним'], [false, 'одним']],
                    ['CASE_PREPOSITIONAL', [true, 'одном'], [false, 'одном']]],
                ['GENDER_FEMININE',
                    ['CASE_NOMINATIVE', [true, 'одна'], [false, 'одна']],
                    ['CASE_GENITIVE', [true, 'одной'], [false, 'одной']],
                    ['CASE_DATIVE', [true, 'одной'], [false, 'одной']],
                    ['CASE_ACCUSATIVE', [true, 'одну'], [false, 'одну']],
                    ['CASE_INSTRUMENTAL', [true, 'одной'], [false, 'одной']],
                    ['CASE_PREPOSITIONAL', [true, 'одной'], [false, 'одной']]],
                ['GENDER_NEUTER',
                    ['CASE_NOMINATIVE', [true, 'одно'], [false, 'одно']],
                    ['CASE_GENITIVE', [true, 'одного'], [false, 'одного']],
                    ['CASE_DATIVE', [true, 'одному'], [false, 'одному']],
                    ['CASE_ACCUSATIVE', [true, 'одно'], [false, 'одно']],
                    ['CASE_INSTRUMENTAL', [true, 'одним'], [false, 'одним']],
                    ['CASE_PREPOSITIONAL', [true, 'одном'], [false, 'одном']]]],
            [2,
                ['GENDER_MASCULINE',
                    ['CASE_NOMINATIVE', [true, 'два'], [false, 'два']],
                    ['CASE_GENITIVE', [true, 'двух'], [false, 'двух']],
                    ['CASE_DATIVE', [true, 'двум'], [false, 'двум']],
                    ['CASE_ACCUSATIVE', [true, 'двух'], [false, 'два']],
                    ['CASE_INSTRUMENTAL', [true, 'двумя'], [false, 'двумя']],
                    ['CASE_PREPOSITIONAL', [true, 'двух'], [false, 'двух']]],
                ['GENDER_FEMININE',
                    ['CASE_NOMINATIVE', [true, 'две'], [false, 'две']],
                    ['CASE_GENITIVE', [true, 'двух'], [false, 'двух']],
                    ['CASE_DATIVE', [true, 'двум'], [false, 'двум']],
                    ['CASE_ACCUSATIVE', [true, 'двух'], [false, 'две']],
                    ['CASE_INSTRUMENTAL', [true, 'двумя'], [false, 'двумя']],
                    ['CASE_PREPOSITIONAL', [true, 'двух'], [false, 'двух']]],
                ['GENDER_NEUTER',
                    ['CASE_NOMINATIVE', [true, 'два'], [false, 'два']],
                    ['CASE_GENITIVE', [true, 'двух'], [false, 'двух']],
                    ['CASE_DATIVE', [true, 'двум'], [false, 'двум']],
                    ['CASE_ACCUSATIVE', [true, 'два'], [false, 'два']],
                    ['CASE_INSTRUMENTAL', [true, 'двумя'], [false, 'двумя']],
                    ['CASE_PREPOSITIONAL', [true, 'двух'], [false, 'двух']]]],
            [3,
                ['GENDER_MASCULINE',
                    ['CASE_NOMINATIVE', [true, 'три'], [false, 'три']],
                    ['CASE_GENITIVE', [true, 'трёх'], [false, 'трёх']],
                    ['CASE_DATIVE', [true, 'трём'], [false, 'трём']],
                    ['CASE_ACCUSATIVE', [true, 'трёх'], [false, 'три']],
                    ['CASE_INSTRUMENTAL', [true, 'тремя'], [false, 'тремя']],
                    ['CASE_PREPOSITIONAL', [true, 'трёх'], [false, 'трёх']]],
                ['GENDER_FEMININE',
                    ['CASE_NOMINATIVE', [true, 'три'], [false, 'три']],
                    ['CASE_GENITIVE', [true, 'трёх'], [false, 'трёх']],
                    ['CASE_DATIVE', [true, 'трём'], [false, 'трём']],
                    ['CASE_ACCUSATIVE', [true, 'трёх'], [false, 'три']],
                    ['CASE_INSTRUMENTAL', [true, 'тремя'], [false, 'тремя']],
                    ['CASE_PREPOSITIONAL', [true, 'трёх'], [false, 'трёх']]],
                ['GENDER_NEUTER',
                    ['CASE_NOMINATIVE', [true, 'три'], [false, 'три']],
                    ['CASE_GENITIVE', [true, 'трёх'], [false, 'трёх']],
                    ['CASE_DATIVE', [true, 'трём'], [false, 'трём']],
                    ['CASE_ACCUSATIVE', [true, 'три'], [false, 'три']],
                    ['CASE_INSTRUMENTAL', [true, 'тремя'], [false, 'тремя']],
                    ['CASE_PREPOSITIONAL', [true, 'трёх'], [false, 'трёх']]]],
            [4,
                ['GENDER_MASCULINE',
                    ['CASE_NOMINATIVE', [true, 'четыре'], [false, 'четыре']],
                    ['CASE_GENITIVE', [true, 'четырёх'], [false, 'четырёх']],
                    ['CASE_DATIVE', [true, 'четырём'], [false, 'четырём']],
                    ['CASE_ACCUSATIVE', [true, 'четырёх'], [false, 'четыре']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'четырьмя'],
                        [false, 'четырьмя']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'четырёх'],
                        [false, 'четырёх']]],
                ['GENDER_FEMININE',
                    ['CASE_NOMINATIVE', [true, 'четыре'], [false, 'четыре']],
                    ['CASE_GENITIVE', [true, 'четырёх'], [false, 'четырёх']],
                    ['CASE_DATIVE', [true, 'четырём'], [false, 'четырём']],
                    ['CASE_ACCUSATIVE', [true, 'четырёх'], [false, 'четыре']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'четырьмя'],
                        [false, 'четырьмя']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'четырёх'],
                        [false, 'четырёх']]],
                ['GENDER_NEUTER',
                    ['CASE_NOMINATIVE', [true, 'четыре'], [false, 'четыре']],
                    ['CASE_GENITIVE', [true, 'четырёх'], [false, 'четырёх']],
                    ['CASE_DATIVE', [true, 'четырём'], [false, 'четырём']],
                    ['CASE_ACCUSATIVE', [true, 'четыре'], [false, 'четыре']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'четырьмя'],
                        [false, 'четырьмя']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'четырёх'],
                        [false, 'четырёх']]]],
            [5,
                ['GENDER_MASCULINE',
                    ['CASE_NOMINATIVE', [true, 'пять'], [false, 'пять']],
                    ['CASE_GENITIVE', [true, 'пяти'], [false, 'пяти']],
                    ['CASE_DATIVE', [true, 'пяти'], [false, 'пяти']],
                    ['CASE_ACCUSATIVE', [true, 'пять'], [false, 'пять']],
                    ['CASE_INSTRUMENTAL', [true, 'пятью'], [false, 'пятью']],
                    ['CASE_PREPOSITIONAL', [true, 'пяти'], [false, 'пяти']]],
                ['GENDER_FEMININE',
                    ['CASE_NOMINATIVE', [true, 'пять'], [false, 'пять']],
                    ['CASE_GENITIVE', [true, 'пяти'], [false, 'пяти']],
                    ['CASE_DATIVE', [true, 'пяти'], [false, 'пяти']],
                    ['CASE_ACCUSATIVE', [true, 'пять'], [false, 'пять']],
                    ['CASE_INSTRUMENTAL', [true, 'пятью'], [false, 'пятью']],
                    ['CASE_PREPOSITIONAL', [true, 'пяти'], [false, 'пяти']]],
                ['GENDER_NEUTER',
                    ['CASE_NOMINATIVE', [true, 'пять'], [false, 'пять']],
                    ['CASE_GENITIVE', [true, 'пяти'], [false, 'пяти']],
                    ['CASE_DATIVE', [true, 'пяти'], [false, 'пяти']],
                    ['CASE_ACCUSATIVE', [true, 'пять'], [false, 'пять']],
                    ['CASE_INSTRUMENTAL', [true, 'пятью'], [false, 'пятью']],
                    ['CASE_PREPOSITIONAL', [true, 'пяти'], [false, 'пяти']]]],
            [6,
                ['GENDER_MASCULINE',
                    ['CASE_NOMINATIVE', [true, 'шесть'], [false, 'шесть']],
                    ['CASE_GENITIVE', [true, 'шести'], [false, 'шести']],
                    ['CASE_DATIVE', [true, 'шести'], [false, 'шести']],
                    ['CASE_ACCUSATIVE', [true, 'шесть'], [false, 'шесть']],
                    ['CASE_INSTRUMENTAL', [true, 'шестью'], [false, 'шестью']],
                    ['CASE_PREPOSITIONAL', [true, 'шести'], [false, 'шести']]],
                ['GENDER_FEMININE',
                    ['CASE_NOMINATIVE', [true, 'шесть'], [false, 'шесть']],
                    ['CASE_GENITIVE', [true, 'шести'], [false, 'шести']],
                    ['CASE_DATIVE', [true, 'шести'], [false, 'шести']],
                    ['CASE_ACCUSATIVE', [true, 'шесть'], [false, 'шесть']],
                    ['CASE_INSTRUMENTAL', [true, 'шестью'], [false, 'шестью']],
                    ['CASE_PREPOSITIONAL', [true, 'шести'], [false, 'шести']]],
                ['GENDER_NEUTER',
                    ['CASE_NOMINATIVE', [true, 'шесть'], [false, 'шесть']],
                    ['CASE_GENITIVE', [true, 'шести'], [false, 'шести']],
                    ['CASE_DATIVE', [true, 'шести'], [false, 'шести']],
                    ['CASE_ACCUSATIVE', [true, 'шесть'], [false, 'шесть']],
                    ['CASE_INSTRUMENTAL', [true, 'шестью'], [false, 'шестью']],
                    ['CASE_PREPOSITIONAL', [true, 'шести'], [false, 'шести']]]],
            [7,
                ['GENDER_MASCULINE',
                    ['CASE_NOMINATIVE', [true, 'семь'], [false, 'семь']],
                    ['CASE_GENITIVE', [true, 'семи'], [false, 'семи']],
                    ['CASE_DATIVE', [true, 'семи'], [false, 'семи']],
                    ['CASE_ACCUSATIVE', [true, 'семь'], [false, 'семь']],
                    ['CASE_INSTRUMENTAL', [true, 'семью'], [false, 'семью']],
                    ['CASE_PREPOSITIONAL', [true, 'семи'], [false, 'семи']]],
                ['GENDER_FEMININE',
                    ['CASE_NOMINATIVE', [true, 'семь'], [false, 'семь']],
                    ['CASE_GENITIVE', [true, 'семи'], [false, 'семи']],
                    ['CASE_DATIVE', [true, 'семи'], [false, 'семи']],
                    ['CASE_ACCUSATIVE', [true, 'семь'], [false, 'семь']],
                    ['CASE_INSTRUMENTAL', [true, 'семью'], [false, 'семью']],
                    ['CASE_PREPOSITIONAL', [true, 'семи'], [false, 'семи']]],
                ['GENDER_NEUTER',
                    ['CASE_NOMINATIVE', [true, 'семь'], [false, 'семь']],
                    ['CASE_GENITIVE', [true, 'семи'], [false, 'семи']],
                    ['CASE_DATIVE', [true, 'семи'], [false, 'семи']],
                    ['CASE_ACCUSATIVE', [true, 'семь'], [false, 'семь']],
                    ['CASE_INSTRUMENTAL', [true, 'семью'], [false, 'семью']],
                    ['CASE_PREPOSITIONAL', [true, 'семи'], [false, 'семи']]]],
            [8,
                ['GENDER_MASCULINE',
                    ['CASE_NOMINATIVE', [true, 'восемь'], [false, 'восемь']],
                    ['CASE_GENITIVE', [true, 'восьми'], [false, 'восьми']],
                    ['CASE_DATIVE', [true, 'восьми'], [false, 'восьми']],
                    ['CASE_ACCUSATIVE', [true, 'восемь'], [false, 'восемь']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'восемью'],
                        [false, 'восемью']],
                    ['CASE_PREPOSITIONAL', [true, 'восьми'], [false, 'восьми']]],
                ['GENDER_FEMININE',
                    ['CASE_NOMINATIVE', [true, 'восемь'], [false, 'восемь']],
                    ['CASE_GENITIVE', [true, 'восьми'], [false, 'восьми']],
                    ['CASE_DATIVE', [true, 'восьми'], [false, 'восьми']],
                    ['CASE_ACCUSATIVE', [true, 'восемь'], [false, 'восемь']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'восемью'],
                        [false, 'восемью']],
                    ['CASE_PREPOSITIONAL', [true, 'восьми'], [false, 'восьми']]],
                ['GENDER_NEUTER',
                    ['CASE_NOMINATIVE', [true, 'восемь'], [false, 'восемь']],
                    ['CASE_GENITIVE', [true, 'восьми'], [false, 'восьми']],
                    ['CASE_DATIVE', [true, 'восьми'], [false, 'восьми']],
                    ['CASE_ACCUSATIVE', [true, 'восемь'], [false, 'восемь']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'восемью'],
                        [false, 'восемью']],
                    ['CASE_PREPOSITIONAL', [true, 'восьми'], [false, 'восьми']]]],
            [9,
                ['GENDER_MASCULINE',
                    ['CASE_NOMINATIVE', [true, 'девять'], [false, 'девять']],
                    ['CASE_GENITIVE', [true, 'девяти'], [false, 'девяти']],
                    ['CASE_DATIVE', [true, 'девяти'], [false, 'девяти']],
                    ['CASE_ACCUSATIVE', [true, 'девять'], [false, 'девять']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'девятью'],
                        [false, 'девятью']],
                    ['CASE_PREPOSITIONAL', [true, 'девяти'], [false, 'девяти']]],
                ['GENDER_FEMININE',
                    ['CASE_NOMINATIVE', [true, 'девять'], [false, 'девять']],
                    ['CASE_GENITIVE', [true, 'девяти'], [false, 'девяти']],
                    ['CASE_DATIVE', [true, 'девяти'], [false, 'девяти']],
                    ['CASE_ACCUSATIVE', [true, 'девять'], [false, 'девять']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'девятью'],
                        [false, 'девятью']],
                    ['CASE_PREPOSITIONAL', [true, 'девяти'], [false, 'девяти']]],
                ['GENDER_NEUTER',
                    ['CASE_NOMINATIVE', [true, 'девять'], [false, 'девять']],
                    ['CASE_GENITIVE', [true, 'девяти'], [false, 'девяти']],
                    ['CASE_DATIVE', [true, 'девяти'], [false, 'девяти']],
                    ['CASE_ACCUSATIVE', [true, 'девять'], [false, 'девять']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'девятью'],
                        [false, 'девятью']],
                    ['CASE_PREPOSITIONAL', [true, 'девяти'], [false, 'девяти']]]],
            [10,
                ['GENDER_MASCULINE',
                    ['CASE_NOMINATIVE', [true, 'десять'], [false, 'десять']],
                    ['CASE_GENITIVE', [true, 'десяти'], [false, 'десяти']],
                    ['CASE_DATIVE', [true, 'десяти'], [false, 'десяти']],
                    ['CASE_ACCUSATIVE', [true, 'десять'], [false, 'десять']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'десятью'],
                        [false, 'десятью']],
                    ['CASE_PREPOSITIONAL', [true, 'десяти'], [false, 'десяти']]],
                ['GENDER_FEMININE',
                    ['CASE_NOMINATIVE', [true, 'десять'], [false, 'десять']],
                    ['CASE_GENITIVE', [true, 'десяти'], [false, 'десяти']],
                    ['CASE_DATIVE', [true, 'десяти'], [false, 'десяти']],
                    ['CASE_ACCUSATIVE', [true, 'десять'], [false, 'десять']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'десятью'],
                        [false, 'десятью']],
                    ['CASE_PREPOSITIONAL', [true, 'десяти'], [false, 'десяти']]],
                ['GENDER_NEUTER',
                    ['CASE_NOMINATIVE', [true, 'десять'], [false, 'десять']],
                    ['CASE_GENITIVE', [true, 'десяти'], [false, 'десяти']],
                    ['CASE_DATIVE', [true, 'десяти'], [false, 'десяти']],
                    ['CASE_ACCUSATIVE', [true, 'десять'], [false, 'десять']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'десятью'],
                        [false, 'десятью']],
                    ['CASE_PREPOSITIONAL', [true, 'десяти'], [false, 'десяти']]]],
            [11,
                ['GENDER_MASCULINE',
                    ['CASE_NOMINATIVE',
                        [true, 'одиннадцать'],
                        [false, 'одиннадцать']],
                    ['CASE_GENITIVE',
                        [true, 'одиннадцати'],
                        [false, 'одиннадцати']],
                    ['CASE_DATIVE',
                        [true, 'одиннадцати'],
                        [false, 'одиннадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'одиннадцать'],
                        [false, 'одиннадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'одиннадцатью'],
                        [false, 'одиннадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'одиннадцати'],
                        [false, 'одиннадцати']]],
                ['GENDER_FEMININE',
                    ['CASE_NOMINATIVE',
                        [true, 'одиннадцать'],
                        [false, 'одиннадцать']],
                    ['CASE_GENITIVE',
                        [true, 'одиннадцати'],
                        [false, 'одиннадцати']],
                    ['CASE_DATIVE',
                        [true, 'одиннадцати'],
                        [false, 'одиннадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'одиннадцать'],
                        [false, 'одиннадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'одиннадцатью'],
                        [false, 'одиннадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'одиннадцати'],
                        [false, 'одиннадцати']]],
                ['GENDER_NEUTER',
                    ['CASE_NOMINATIVE',
                        [true, 'одиннадцать'],
                        [false, 'одиннадцать']],
                    ['CASE_GENITIVE',
                        [true, 'одиннадцати'],
                        [false, 'одиннадцати']],
                    ['CASE_DATIVE',
                        [true, 'одиннадцати'],
                        [false, 'одиннадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'одиннадцать'],
                        [false, 'одиннадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'одиннадцатью'],
                        [false, 'одиннадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'одиннадцати'],
                        [false, 'одиннадцати']]]],
            [12,
                ['GENDER_MASCULINE',
                    ['CASE_NOMINATIVE',
                        [true, 'двенадцать'],
                        [false, 'двенадцать']],
                    ['CASE_GENITIVE',
                        [true, 'двенадцати'],
                        [false, 'двенадцати']],
                    ['CASE_DATIVE',
                        [true, 'двенадцати'],
                        [false, 'двенадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'двенадцать'],
                        [false, 'двенадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'двенадцатью'],
                        [false, 'двенадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'двенадцати'],
                        [false, 'двенадцати']]],
                ['GENDER_FEMININE',
                    ['CASE_NOMINATIVE',
                        [true, 'двенадцать'],
                        [false, 'двенадцать']],
                    ['CASE_GENITIVE',
                        [true, 'двенадцати'],
                        [false, 'двенадцати']],
                    ['CASE_DATIVE',
                        [true, 'двенадцати'],
                        [false, 'двенадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'двенадцать'],
                        [false, 'двенадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'двенадцатью'],
                        [false, 'двенадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'двенадцати'],
                        [false, 'двенадцати']]],
                ['GENDER_NEUTER',
                    ['CASE_NOMINATIVE',
                        [true, 'двенадцать'],
                        [false, 'двенадцать']],
                    ['CASE_GENITIVE',
                        [true, 'двенадцати'],
                        [false, 'двенадцати']],
                    ['CASE_DATIVE',
                        [true, 'двенадцати'],
                        [false, 'двенадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'двенадцать'],
                        [false, 'двенадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'двенадцатью'],
                        [false, 'двенадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'двенадцати'],
                        [false, 'двенадцати']]]],
            [13,
                ['GENDER_MASCULINE',
                    ['CASE_NOMINATIVE',
                        [true, 'тринадцать'],
                        [false, 'тринадцать']],
                    ['CASE_GENITIVE',
                        [true, 'тринадцати'],
                        [false, 'тринадцати']],
                    ['CASE_DATIVE',
                        [true, 'тринадцати'],
                        [false, 'тринадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'тринадцать'],
                        [false, 'тринадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'тринадцатью'],
                        [false, 'тринадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'тринадцати'],
                        [false, 'тринадцати']]],
                ['GENDER_FEMININE',
                    ['CASE_NOMINATIVE',
                        [true, 'тринадцать'],
                        [false, 'тринадцать']],
                    ['CASE_GENITIVE',
                        [true, 'тринадцати'],
                        [false, 'тринадцати']],
                    ['CASE_DATIVE',
                        [true, 'тринадцати'],
                        [false, 'тринадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'тринадцать'],
                        [false, 'тринадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'тринадцатью'],
                        [false, 'тринадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'тринадцати'],
                        [false, 'тринадцати']]],
                ['GENDER_NEUTER',
                    ['CASE_NOMINATIVE',
                        [true, 'тринадцать'],
                        [false, 'тринадцать']],
                    ['CASE_GENITIVE',
                        [true, 'тринадцати'],
                        [false, 'тринадцати']],
                    ['CASE_DATIVE',
                        [true, 'тринадцати'],
                        [false, 'тринадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'тринадцать'],
                        [false, 'тринадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'тринадцатью'],
                        [false, 'тринадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'тринадцати'],
                        [false, 'тринадцати']]]],
            [14,
                ['GENDER_MASCULINE',
                    ['CASE_NOMINATIVE',
                        [true, 'четырнадцать'],
                        [false, 'четырнадцать']],
                    ['CASE_GENITIVE',
                        [true, 'четырнадцати'],
                        [false, 'четырнадцати']],
                    ['CASE_DATIVE',
                        [true, 'четырнадцати'],
                        [false, 'четырнадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'четырнадцать'],
                        [false, 'четырнадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'четырнадцатью'],
                        [false, 'четырнадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'четырнадцати'],
                        [false, 'четырнадцати']]],
                ['GENDER_FEMININE',
                    ['CASE_NOMINATIVE',
                        [true, 'четырнадцать'],
                        [false, 'четырнадцать']],
                    ['CASE_GENITIVE',
                        [true, 'четырнадцати'],
                        [false, 'четырнадцати']],
                    ['CASE_DATIVE',
                        [true, 'четырнадцати'],
                        [false, 'четырнадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'четырнадцать'],
                        [false, 'четырнадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'четырнадцатью'],
                        [false, 'четырнадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'четырнадцати'],
                        [false, 'четырнадцати']]],
                ['GENDER_NEUTER',
                    ['CASE_NOMINATIVE',
                        [true, 'четырнадцать'],
                        [false, 'четырнадцать']],
                    ['CASE_GENITIVE',
                        [true, 'четырнадцати'],
                        [false, 'четырнадцати']],
                    ['CASE_DATIVE',
                        [true, 'четырнадцати'],
                        [false, 'четырнадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'четырнадцать'],
                        [false, 'четырнадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'четырнадцатью'],
                        [false, 'четырнадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'четырнадцати'],
                        [false, 'четырнадцати']]]],
            [15,
                ['GENDER_MASCULINE',
                    ['CASE_NOMINATIVE',
                        [true, 'пятнадцать'],
                        [false, 'пятнадцать']],
                    ['CASE_GENITIVE',
                        [true, 'пятнадцати'],
                        [false, 'пятнадцати']],
                    ['CASE_DATIVE',
                        [true, 'пятнадцати'],
                        [false, 'пятнадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'пятнадцать'],
                        [false, 'пятнадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'пятнадцатью'],
                        [false, 'пятнадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'пятнадцати'],
                        [false, 'пятнадцати']]],
                ['GENDER_FEMININE',
                    ['CASE_NOMINATIVE',
                        [true, 'пятнадцать'],
                        [false, 'пятнадцать']],
                    ['CASE_GENITIVE',
                        [true, 'пятнадцати'],
                        [false, 'пятнадцати']],
                    ['CASE_DATIVE',
                        [true, 'пятнадцати'],
                        [false, 'пятнадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'пятнадцать'],
                        [false, 'пятнадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'пятнадцатью'],
                        [false, 'пятнадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'пятнадцати'],
                        [false, 'пятнадцати']]],
                ['GENDER_NEUTER',
                    ['CASE_NOMINATIVE',
                        [true, 'пятнадцать'],
                        [false, 'пятнадцать']],
                    ['CASE_GENITIVE',
                        [true, 'пятнадцати'],
                        [false, 'пятнадцати']],
                    ['CASE_DATIVE',
                        [true, 'пятнадцати'],
                        [false, 'пятнадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'пятнадцать'],
                        [false, 'пятнадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'пятнадцатью'],
                        [false, 'пятнадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'пятнадцати'],
                        [false, 'пятнадцати']]]],
            [16,
                ['GENDER_MASCULINE',
                    ['CASE_NOMINATIVE',
                        [true, 'шестнадцать'],
                        [false, 'шестнадцать']],
                    ['CASE_GENITIVE',
                        [true, 'шестнадцати'],
                        [false, 'шестнадцати']],
                    ['CASE_DATIVE',
                        [true, 'шестнадцати'],
                        [false, 'шестнадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'шестнадцать'],
                        [false, 'шестнадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'шестнадцатью'],
                        [false, 'шестнадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'шестнадцати'],
                        [false, 'шестнадцати']]],
                ['GENDER_FEMININE',
                    ['CASE_NOMINATIVE',
                        [true, 'шестнадцать'],
                        [false, 'шестнадцать']],
                    ['CASE_GENITIVE',
                        [true, 'шестнадцати'],
                        [false, 'шестнадцати']],
                    ['CASE_DATIVE',
                        [true, 'шестнадцати'],
                        [false, 'шестнадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'шестнадцать'],
                        [false, 'шестнадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'шестнадцатью'],
                        [false, 'шестнадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'шестнадцати'],
                        [false, 'шестнадцати']]],
                ['GENDER_NEUTER',
                    ['CASE_NOMINATIVE',
                        [true, 'шестнадцать'],
                        [false, 'шестнадцать']],
                    ['CASE_GENITIVE',
                        [true, 'шестнадцати'],
                        [false, 'шестнадцати']],
                    ['CASE_DATIVE',
                        [true, 'шестнадцати'],
                        [false, 'шестнадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'шестнадцать'],
                        [false, 'шестнадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'шестнадцатью'],
                        [false, 'шестнадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'шестнадцати'],
                        [false, 'шестнадцати']]]],
            [17,
                ['GENDER_MASCULINE',
                    ['CASE_NOMINATIVE',
                        [true, 'семнадцать'],
                        [false, 'семнадцать']],
                    ['CASE_GENITIVE',
                        [true, 'семнадцати'],
                        [false, 'семнадцати']],
                    ['CASE_DATIVE',
                        [true, 'семнадцати'],
                        [false, 'семнадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'семнадцать'],
                        [false, 'семнадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'семнадцатью'],
                        [false, 'семнадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'семнадцати'],
                        [false, 'семнадцати']]],
                ['GENDER_FEMININE',
                    ['CASE_NOMINATIVE',
                        [true, 'семнадцать'],
                        [false, 'семнадцать']],
                    ['CASE_GENITIVE',
                        [true, 'семнадцати'],
                        [false, 'семнадцати']],
                    ['CASE_DATIVE',
                        [true, 'семнадцати'],
                        [false, 'семнадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'семнадцать'],
                        [false, 'семнадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'семнадцатью'],
                        [false, 'семнадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'семнадцати'],
                        [false, 'семнадцати']]],
                ['GENDER_NEUTER',
                    ['CASE_NOMINATIVE',
                        [true, 'семнадцать'],
                        [false, 'семнадцать']],
                    ['CASE_GENITIVE',
                        [true, 'семнадцати'],
                        [false, 'семнадцати']],
                    ['CASE_DATIVE',
                        [true, 'семнадцати'],
                        [false, 'семнадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'семнадцать'],
                        [false, 'семнадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'семнадцатью'],
                        [false, 'семнадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'семнадцати'],
                        [false, 'семнадцати']]]],
            [18,
                ['GENDER_MASCULINE',
                    ['CASE_NOMINATIVE',
                        [true, 'восемнадцать'],
                        [false, 'восемнадцать']],
                    ['CASE_GENITIVE',
                        [true, 'восемнадцати'],
                        [false, 'восемнадцати']],
                    ['CASE_DATIVE',
                        [true, 'восемнадцати'],
                        [false, 'восемнадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'восемнадцать'],
                        [false, 'восемнадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'восемнадцатью'],
                        [false, 'восемнадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'восемнадцати'],
                        [false, 'восемнадцати']]],
                ['GENDER_FEMININE',
                    ['CASE_NOMINATIVE',
                        [true, 'восемнадцать'],
                        [false, 'восемнадцать']],
                    ['CASE_GENITIVE',
                        [true, 'восемнадцати'],
                        [false, 'восемнадцати']],
                    ['CASE_DATIVE',
                        [true, 'восемнадцати'],
                        [false, 'восемнадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'восемнадцать'],
                        [false, 'восемнадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'восемнадцатью'],
                        [false, 'восемнадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'восемнадцати'],
                        [false, 'восемнадцати']]],
                ['GENDER_NEUTER',
                    ['CASE_NOMINATIVE',
                        [true, 'восемнадцать'],
                        [false, 'восемнадцать']],
                    ['CASE_GENITIVE',
                        [true, 'восемнадцати'],
                        [false, 'восемнадцати']],
                    ['CASE_DATIVE',
                        [true, 'восемнадцати'],
                        [false, 'восемнадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'восемнадцать'],
                        [false, 'восемнадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'восемнадцатью'],
                        [false, 'восемнадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'восемнадцати'],
                        [false, 'восемнадцати']]]],
            [19,
                ['GENDER_MASCULINE',
                    ['CASE_NOMINATIVE',
                        [true, 'девятнадцать'],
                        [false, 'девятнадцать']],
                    ['CASE_GENITIVE',
                        [true, 'девятнадцати'],
                        [false, 'девятнадцати']],
                    ['CASE_DATIVE',
                        [true, 'девятнадцати'],
                        [false, 'девятнадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'девятнадцать'],
                        [false, 'девятнадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'девятнадцатью'],
                        [false, 'девятнадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'девятнадцати'],
                        [false, 'девятнадцати']]],
                ['GENDER_FEMININE',
                    ['CASE_NOMINATIVE',
                        [true, 'девятнадцать'],
                        [false, 'девятнадцать']],
                    ['CASE_GENITIVE',
                        [true, 'девятнадцати'],
                        [false, 'девятнадцати']],
                    ['CASE_DATIVE',
                        [true, 'девятнадцати'],
                        [false, 'девятнадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'девятнадцать'],
                        [false, 'девятнадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'девятнадцатью'],
                        [false, 'девятнадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'девятнадцати'],
                        [false, 'девятнадцати']]],
                ['GENDER_NEUTER',
                    ['CASE_NOMINATIVE',
                        [true, 'девятнадцать'],
                        [false, 'девятнадцать']],
                    ['CASE_GENITIVE',
                        [true, 'девятнадцати'],
                        [false, 'девятнадцати']],
                    ['CASE_DATIVE',
                        [true, 'девятнадцати'],
                        [false, 'девятнадцати']],
                    ['CASE_ACCUSATIVE',
                        [true, 'девятнадцать'],
                        [false, 'девятнадцать']],
                    ['CASE_INSTRUMENTAL',
                        [true, 'девятнадцатью'],
                        [false, 'девятнадцатью']],
                    ['CASE_PREPOSITIONAL',
                        [true, 'девятнадцати'],
                        [false, 'девятнадцати']]]]
        ],
        ['10, 20,.. 90 (tens)'].concat(
            [
                [20, 'двадцать', 'двадцати', 'двадцати', 'двадцать', 'двадцатью', 'двадцати'],
                [30, 'тридцать', 'тридцати', 'тридцати', 'тридцать', 'тридцатью', 'тридцати'],
                [40, 'сорок', 'сорока', 'сорока', 'сорок', 'сорока', 'сорока'],
                [50, 'пятьдесят', 'пятидесяти', 'пятидесяти', 'пятьдесят', 'пятьюдесятью', 'пятидесяти'],
                [60, 'шестьдесят', 'шестидесяти', 'шестидесяти', 'шестьдесят', 'шестьюдесятью', 'шестидесяти'],
                [70, 'семьдесят', 'семидесяти', 'семидесяти', 'семьдесят', 'семьюдесятью', 'семидесяти'],
                [80, 'восемьдесят', 'восьмидесяти', 'восьмидесяти', 'восемьдесят', 'восемьюдесятью', 'восьмидесяти'],
                [90, 'девяносто', 'девяноста', 'девяноста', 'девяносто', 'девяноста', 'девяноста']
            ].map(ten => [ten.shift()].concat(
                ['GENDER_MASCULINE', 'GENDER_FEMiNINE', 'GENDER_NEUTER'].map(gender => [gender].concat(
                    [
                        'CASE_NOMINATIVE',
                        'CASE_GENITIVE',
                        'CASE_DATIVE',
                        'CASE_ACCUSATIVE',
                        'CASE_INSTRUMENTAL',
                        'CASE_PREPOSITIONAL'
                    ].map((kase, i) => [kase, [true, ten[i]], [false, ten[i]]])
                ))
            ))
        ),
        ['100, 200,.. 900 (hundreds)'].concat(
            [
                [100, 'сто', 'ста', 'ста', 'сто', 'ста', 'ста'],
                [200, 'двести', 'двухсот', 'двумстам', 'двести', 'двумястами', 'двухстах'],
                [300, 'триста', 'трёхсот', 'трёмстам', 'триста', 'тремястами', 'трёхстах'],
                [400, 'четыреста', 'четырёхсот', 'четырёмстам', 'четыреста', 'четырьмястами', 'четырёхстах'],
                [500, 'пятьсот', 'пятисот', 'пятистам', 'пятьсот', 'пятьюстами', 'пятистах'],
                [600, 'шестьсот', 'шестисот', 'шестистам', 'шестьсот', 'шестьюстами', 'шестистах'],
                [700, 'семьсот', 'семисот', 'семистам', 'семьсот', 'семьюстами', 'семистах'],
                [800, 'восемьсот', 'восьмисот', 'восьмистам', 'восемьсот', 'восемьюстами', 'восьмистах'],
                [900, 'девятьсот', 'девятисот', 'девятистам', 'девятьсот', 'девятьюстами', 'девятистах']
            ].map(ten => [ten.shift()].concat(
                ['GENDER_MASCULINE', 'GENDER_FEMiNINE', 'GENDER_NEUTER'].map(gender => [gender].concat(
                    [
                        'CASE_NOMINATIVE',
                        'CASE_GENITIVE',
                        'CASE_DATIVE',
                        'CASE_ACCUSATIVE',
                        'CASE_INSTRUMENTAL',
                        'CASE_PREPOSITIONAL'
                    ].map((kase, i) => [kase, [true, ten[i]], [false, ten[i]]])
                ))
            ))
        ),
        ['1000'].concat(
            [
                [1000, 'одна тысяча', 'одной тысячи', 'одной тысяче', 'одну тысячу', 'одной тысячей', 'одной тысяче'],
                [2000, 'две тысячи', 'двух тысяч', 'двум тысячам', 'две тысячи', 'двумя тысячами', 'двух тысячах'],
                [5000, 'пять тысяч', 'пяти тысяч', 'пяти тысячам', 'пять тысяч', 'пятью тысячами', 'пяти тысячах']
            ].map(item => [item.shift()].concat(
                ['GENDER_MASCULINE', 'GENDER_FEMiNINE', 'GENDER_NEUTER'].map(gender => [gender].concat(
                    [
                        'CASE_NOMINATIVE',
                        'CASE_GENITIVE',
                        'CASE_DATIVE',
                        'CASE_ACCUSATIVE',
                        'CASE_INSTRUMENTAL',
                        'CASE_PREPOSITIONAL'
                    ].map((kase, i) => [kase, [true, item[i]], [false, item[i]]])
                ))
            ))
        ),
        ['1000^2'].concat(
            [
                [1000000,
                    'один миллион',
                    'одного миллиона',
                    'одному миллиону',
                    'один миллион',
                    'одним миллионом',
                    'одном миллионе'
                ],
                [2000000,
                    'два миллиона',
                    'двух миллионов',
                    'двум миллионам',
                    'два миллиона',
                    'двумя миллионами',
                    'двух миллионах'
                ],
                [5000000,
                    'пять миллионов',
                    'пяти миллионов',
                    'пяти миллионам',
                    'пять миллионов',
                    'пятью миллионами',
                    'пяти миллионах'
                ]
            ].map(item => [item.shift()].concat(
                ['GENDER_MASCULINE', 'GENDER_FEMiNINE', 'GENDER_NEUTER'].map(gender => [gender].concat(
                    [
                        'CASE_NOMINATIVE',
                        'CASE_GENITIVE',
                        'CASE_DATIVE',
                        'CASE_ACCUSATIVE',
                        'CASE_INSTRUMENTAL',
                        'CASE_PREPOSITIONAL'
                    ].map((kase, i) => [kase, [true, item[i]], [false, item[i]]])
                ))
            ))
        ),
        ['1000^3'].concat(
            [
                [1000000000,
                    'один миллиард',
                    'одного миллиарда',
                    'одному миллиарду',
                    'один миллиард',
                    'одним миллиардом',
                    'одном миллиарде'
                ],
                [2000000000,
                    'два миллиарда',
                    'двух миллиардов',
                    'двум миллиардам',
                    'два миллиарда',
                    'двумя миллиардами',
                    'двух миллиардах'
                ],
                [5000000000,
                    'пять миллиардов',
                    'пяти миллиардов',
                    'пяти миллиардам',
                    'пять миллиардов',
                    'пятью миллиардами',
                    'пяти миллиардах'
                ]
            ].map(item => [item.shift()].concat(
                ['GENDER_MASCULINE', 'GENDER_FEMiNINE', 'GENDER_NEUTER'].map(gender => [gender].concat(
                    [
                        'CASE_NOMINATIVE',
                        'CASE_GENITIVE',
                        'CASE_DATIVE',
                        'CASE_ACCUSATIVE',
                        'CASE_INSTRUMENTAL',
                        'CASE_PREPOSITIONAL'
                    ].map((kase, i) => [kase, [true, item[i]], [false, item[i]]])
                ))
            ))
        ),
        ['1000^4'].concat(
            [
                [1000000000000,
                    'один триллион',
                    'одного триллиона',
                    'одному триллиону',
                    'один триллион',
                    'одним триллионом',
                    'одном триллионе'
                ],
                [2000000000000,
                    'два триллиона',
                    'двух триллионов',
                    'двум триллионам',
                    'два триллиона',
                    'двумя триллионами',
                    'двух триллионах'
                ],
                [5000000000000,
                    'пять триллионов',
                    'пяти триллионов',
                    'пяти триллионам',
                    'пять триллионов',
                    'пятью триллионами',
                    'пяти триллионах'
                ]
            ].map(item => [item.shift()].concat(
                ['GENDER_MASCULINE', 'GENDER_FEMiNINE', 'GENDER_NEUTER'].map(gender => [gender].concat(
                    [
                        'CASE_NOMINATIVE',
                        'CASE_GENITIVE',
                        'CASE_DATIVE',
                        'CASE_ACCUSATIVE',
                        'CASE_INSTRUMENTAL',
                        'CASE_PREPOSITIONAL'
                    ].map((kase, i) => [kase, [true, item[i]], [false, item[i]]])
                ))
            ))
        ),
        ['misc',
            [5122981121,
                ['GENDER_MASCULINE',
                    ['CASE_NOMINATIVE',
                        [true, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одна тысяча сто двадцать один'],
                        [false, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одна тысяча сто двадцать один']
                    ],
                    ['CASE_GENITIVE',
                        [true, 'пяти миллиардов ста двадцати двух миллионов девятисот восьмидесяти одной тысячи ста двадцати одного'],
                        [false, 'пяти миллиардов ста двадцати двух миллионов девятисот восьмидесяти одной тысячи ста двадцати одного']
                    ],
                    ['CASE_DATIVE',
                        [true, 'пяти миллиардам ста двадцати двум миллионам девятистам восьмидесяти одной тысяче ста двадцати одному'],
                        [false, 'пяти миллиардам ста двадцати двум миллионам девятистам восьмидесяти одной тысяче ста двадцати одному']
                    ],
                    ['CASE_ACCUSATIVE',
                        [true, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одну тысячу сто двадцать одного'],
                        [false, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одну тысячу сто двадцать один']
                    ],
                    ['CASE_INSTRUMENTAL',
                        [true, 'пятью миллиардами ста двадцатью двумя миллионами девятьюстами восемьюдесятью одной тысячей ста двадцатью одним'],
                        [false, 'пятью миллиардами ста двадцатью двумя миллионами девятьюстами восемьюдесятью одной тысячей ста двадцатью одним']
                    ],
                    ['CASE_PREPOSITIONAL',
                        [true, 'пяти миллиардах ста двадцати двух миллионах девятистах восьмидесяти одной тысяче ста двадцати одном'],
                        [false, 'пяти миллиардах ста двадцати двух миллионах девятистах восьмидесяти одной тысяче ста двадцати одном']
                    ]
                ],
                ['GENDER_FEMININE',
                    ['CASE_NOMINATIVE',
                        [true, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одна тысяча сто двадцать одна'],
                        [false, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одна тысяча сто двадцать одна']
                    ],
                    ['CASE_GENITIVE',
                        [true, 'пяти миллиардов ста двадцати двух миллионов девятисот восьмидесяти одной тысячи ста двадцати одной'],
                        [false, 'пяти миллиардов ста двадцати двух миллионов девятисот восьмидесяти одной тысячи ста двадцати одной']
                    ],
                    ['CASE_DATIVE',
                        [true, 'пяти миллиардам ста двадцати двум миллионам девятистам восьмидесяти одной тысяче ста двадцати одной'],
                        [false, 'пяти миллиардам ста двадцати двум миллионам девятистам восьмидесяти одной тысяче ста двадцати одной']
                    ],
                    ['CASE_ACCUSATIVE',
                        [true, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одну тысячу сто двадцать одну'],
                        [false, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одну тысячу сто двадцать одну']
                    ],
                    ['CASE_INSTRUMENTAL',
                        [true, 'пятью миллиардами ста двадцатью двумя миллионами девятьюстами восемьюдесятью одной тысячей ста двадцатью одной'],
                        [false, 'пятью миллиардами ста двадцатью двумя миллионами девятьюстами восемьюдесятью одной тысячей ста двадцатью одной']
                    ],
                    ['CASE_PREPOSITIONAL',
                        [true, 'пяти миллиардах ста двадцати двух миллионах девятистах восьмидесяти одной тысяче ста двадцати одной'],
                        [false, 'пяти миллиардах ста двадцати двух миллионах девятистах восьмидесяти одной тысяче ста двадцати одной']
                    ]
                ],
                ['GENDER_NEUTER',
                    ['CASE_NOMINATIVE',
                        [true, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одна тысяча сто двадцать одно'],
                        [false, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одна тысяча сто двадцать одно']
                    ],
                    ['CASE_GENITIVE',
                        [true, 'пяти миллиардов ста двадцати двух миллионов девятисот восьмидесяти одной тысячи ста двадцати одного'],
                        [false, 'пяти миллиардов ста двадцати двух миллионов девятисот восьмидесяти одной тысячи ста двадцати одного']
                    ],
                    ['CASE_DATIVE',
                        [true, 'пяти миллиардам ста двадцати двум миллионам девятистам восьмидесяти одной тысяче ста двадцати одному'],
                        [false, 'пяти миллиардам ста двадцати двум миллионам девятистам восьмидесяти одной тысяче ста двадцати одному']
                    ],
                    ['CASE_ACCUSATIVE',
                        [true, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одну тысячу сто двадцать одно'],
                        [false, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одну тысячу сто двадцать одно']
                    ],
                    ['CASE_INSTRUMENTAL',
                        [true, 'пятью миллиардами ста двадцатью двумя миллионами девятьюстами восемьюдесятью одной тысячей ста двадцатью одним'],
                        [false, 'пятью миллиардами ста двадцатью двумя миллионами девятьюстами восемьюдесятью одной тысячей ста двадцатью одним']
                    ],
                    ['CASE_PREPOSITIONAL',
                        [true, 'пяти миллиардах ста двадцати двух миллионах девятистах восьмидесяти одной тысяче ста двадцати одном'],
                        [false, 'пяти миллиардах ста двадцати двух миллионах девятистах восьмидесяти одной тысяче ста двадцати одном']
                    ]
                ]
            ]
        ]
    ];

    tests.map(test => {
        let title = test.shift();
        describe(title, () => {
            test.map(test => {
                let arg0 = test.shift();
                test.map(test => {
                    let arg1 = test.shift();
                    test.map(test => {
                        let arg2 = test.shift();
                        test.map(test => {
                            let arg3 = test.shift();
                            const expected = test.shift();
                            it(`(${arg0}, ${arg1}, ${arg2}, ${arg3}) → ${expected}`, () => {
                                assert.strictEqual(
                                    numeralize(
                                        arg0,
                                        numeralize[arg1],
                                        numeralize[arg2],
                                        arg3
                                    ),
                                    expected
                                );
                            });
                        });
                    });
                });
            });
        });
    });

});
