import {Case, Gender, numeralize} from "./index";
import * as assert from "assert";

describe(numeralize.name, () => {
  type SimpleTestCase = Array<string>;
  type ComplexTestCase = Array<[Gender, ...Array<[Case, [true, string], [false, string]]>]>;

  function isComplex(testCase: SimpleTestCase | ComplexTestCase): testCase is ComplexTestCase {
    return Array.isArray(testCase[0])
  }

  const testCases: Array<
      [string, ...Array<
        [number, ...(SimpleTestCase | ComplexTestCase)]
      >]
    > = [
      ['0 to 19 (minors)',
        [1,
          [Gender.Masculine,
            [Case.Nominative, [true, 'один'], [false, 'один']],
            [Case.Genitive, [true, 'одного'], [false, 'одного']],
            [Case.Dative, [true, 'одному'], [false, 'одному']],
            [Case.Accusative, [true, 'одного'], [false, 'один']],
            [Case.Instrumental, [true, 'одним'], [false, 'одним']],
            [Case.Prepositional, [true, 'одном'], [false, 'одном']]],
          [Gender.Feminine,
            [Case.Nominative, [true, 'одна'], [false, 'одна']],
            [Case.Genitive, [true, 'одной'], [false, 'одной']],
            [Case.Dative, [true, 'одной'], [false, 'одной']],
            [Case.Accusative, [true, 'одну'], [false, 'одну']],
            [Case.Instrumental, [true, 'одной'], [false, 'одной']],
            [Case.Prepositional, [true, 'одной'], [false, 'одной']]],
          [Gender.Neuter,
            [Case.Nominative, [true, 'одно'], [false, 'одно']],
            [Case.Genitive, [true, 'одного'], [false, 'одного']],
            [Case.Dative, [true, 'одному'], [false, 'одному']],
            [Case.Accusative, [true, 'одно'], [false, 'одно']],
            [Case.Instrumental, [true, 'одним'], [false, 'одним']],
            [Case.Prepositional, [true, 'одном'], [false, 'одном']]]],
        [2,
          [Gender.Masculine,
            [Case.Nominative, [true, 'два'], [false, 'два']],
            [Case.Genitive, [true, 'двух'], [false, 'двух']],
            [Case.Dative, [true, 'двум'], [false, 'двум']],
            [Case.Accusative, [true, 'двух'], [false, 'два']],
            [Case.Instrumental, [true, 'двумя'], [false, 'двумя']],
            [Case.Prepositional, [true, 'двух'], [false, 'двух']]],
          [Gender.Feminine,
            [Case.Nominative, [true, 'две'], [false, 'две']],
            [Case.Genitive, [true, 'двух'], [false, 'двух']],
            [Case.Dative, [true, 'двум'], [false, 'двум']],
            [Case.Accusative, [true, 'двух'], [false, 'две']],
            [Case.Instrumental, [true, 'двумя'], [false, 'двумя']],
            [Case.Prepositional, [true, 'двух'], [false, 'двух']]],
          [Gender.Neuter,
            [Case.Nominative, [true, 'два'], [false, 'два']],
            [Case.Genitive, [true, 'двух'], [false, 'двух']],
            [Case.Dative, [true, 'двум'], [false, 'двум']],
            [Case.Accusative, [true, 'два'], [false, 'два']],
            [Case.Instrumental, [true, 'двумя'], [false, 'двумя']],
            [Case.Prepositional, [true, 'двух'], [false, 'двух']]]],
        [3,
          [Gender.Masculine,
            [Case.Nominative, [true, 'три'], [false, 'три']],
            [Case.Genitive, [true, 'трёх'], [false, 'трёх']],
            [Case.Dative, [true, 'трём'], [false, 'трём']],
            [Case.Accusative, [true, 'трёх'], [false, 'три']],
            [Case.Instrumental, [true, 'тремя'], [false, 'тремя']],
            [Case.Prepositional, [true, 'трёх'], [false, 'трёх']]],
          [Gender.Feminine,
            [Case.Nominative, [true, 'три'], [false, 'три']],
            [Case.Genitive, [true, 'трёх'], [false, 'трёх']],
            [Case.Dative, [true, 'трём'], [false, 'трём']],
            [Case.Accusative, [true, 'трёх'], [false, 'три']],
            [Case.Instrumental, [true, 'тремя'], [false, 'тремя']],
            [Case.Prepositional, [true, 'трёх'], [false, 'трёх']]],
          [Gender.Neuter,
            [Case.Nominative, [true, 'три'], [false, 'три']],
            [Case.Genitive, [true, 'трёх'], [false, 'трёх']],
            [Case.Dative, [true, 'трём'], [false, 'трём']],
            [Case.Accusative, [true, 'три'], [false, 'три']],
            [Case.Instrumental, [true, 'тремя'], [false, 'тремя']],
            [Case.Prepositional, [true, 'трёх'], [false, 'трёх']]]],
        [4,
          [Gender.Masculine,
            [Case.Nominative, [true, 'четыре'], [false, 'четыре']],
            [Case.Genitive, [true, 'четырёх'], [false, 'четырёх']],
            [Case.Dative, [true, 'четырём'], [false, 'четырём']],
            [Case.Accusative, [true, 'четырёх'], [false, 'четыре']],
            [Case.Instrumental,
              [true, 'четырьмя'],
              [false, 'четырьмя']],
            [Case.Prepositional,
              [true, 'четырёх'],
              [false, 'четырёх']]],
          [Gender.Feminine,
            [Case.Nominative, [true, 'четыре'], [false, 'четыре']],
            [Case.Genitive, [true, 'четырёх'], [false, 'четырёх']],
            [Case.Dative, [true, 'четырём'], [false, 'четырём']],
            [Case.Accusative, [true, 'четырёх'], [false, 'четыре']],
            [Case.Instrumental,
              [true, 'четырьмя'],
              [false, 'четырьмя']],
            [Case.Prepositional,
              [true, 'четырёх'],
              [false, 'четырёх']]],
          [Gender.Neuter,
            [Case.Nominative, [true, 'четыре'], [false, 'четыре']],
            [Case.Genitive, [true, 'четырёх'], [false, 'четырёх']],
            [Case.Dative, [true, 'четырём'], [false, 'четырём']],
            [Case.Accusative, [true, 'четыре'], [false, 'четыре']],
            [Case.Instrumental,
              [true, 'четырьмя'],
              [false, 'четырьмя']],
            [Case.Prepositional,
              [true, 'четырёх'],
              [false, 'четырёх']]]],
        [5,
          [Gender.Masculine,
            [Case.Nominative, [true, 'пять'], [false, 'пять']],
            [Case.Genitive, [true, 'пяти'], [false, 'пяти']],
            [Case.Dative, [true, 'пяти'], [false, 'пяти']],
            [Case.Accusative, [true, 'пять'], [false, 'пять']],
            [Case.Instrumental, [true, 'пятью'], [false, 'пятью']],
            [Case.Prepositional, [true, 'пяти'], [false, 'пяти']]],
          [Gender.Feminine,
            [Case.Nominative, [true, 'пять'], [false, 'пять']],
            [Case.Genitive, [true, 'пяти'], [false, 'пяти']],
            [Case.Dative, [true, 'пяти'], [false, 'пяти']],
            [Case.Accusative, [true, 'пять'], [false, 'пять']],
            [Case.Instrumental, [true, 'пятью'], [false, 'пятью']],
            [Case.Prepositional, [true, 'пяти'], [false, 'пяти']]],
          [Gender.Neuter,
            [Case.Nominative, [true, 'пять'], [false, 'пять']],
            [Case.Genitive, [true, 'пяти'], [false, 'пяти']],
            [Case.Dative, [true, 'пяти'], [false, 'пяти']],
            [Case.Accusative, [true, 'пять'], [false, 'пять']],
            [Case.Instrumental, [true, 'пятью'], [false, 'пятью']],
            [Case.Prepositional, [true, 'пяти'], [false, 'пяти']]]],
        [6,
          [Gender.Masculine,
            [Case.Nominative, [true, 'шесть'], [false, 'шесть']],
            [Case.Genitive, [true, 'шести'], [false, 'шести']],
            [Case.Dative, [true, 'шести'], [false, 'шести']],
            [Case.Accusative, [true, 'шесть'], [false, 'шесть']],
            [Case.Instrumental, [true, 'шестью'], [false, 'шестью']],
            [Case.Prepositional, [true, 'шести'], [false, 'шести']]],
          [Gender.Feminine,
            [Case.Nominative, [true, 'шесть'], [false, 'шесть']],
            [Case.Genitive, [true, 'шести'], [false, 'шести']],
            [Case.Dative, [true, 'шести'], [false, 'шести']],
            [Case.Accusative, [true, 'шесть'], [false, 'шесть']],
            [Case.Instrumental, [true, 'шестью'], [false, 'шестью']],
            [Case.Prepositional, [true, 'шести'], [false, 'шести']]],
          [Gender.Neuter,
            [Case.Nominative, [true, 'шесть'], [false, 'шесть']],
            [Case.Genitive, [true, 'шести'], [false, 'шести']],
            [Case.Dative, [true, 'шести'], [false, 'шести']],
            [Case.Accusative, [true, 'шесть'], [false, 'шесть']],
            [Case.Instrumental, [true, 'шестью'], [false, 'шестью']],
            [Case.Prepositional, [true, 'шести'], [false, 'шести']]]],
        [7,
          [Gender.Masculine,
            [Case.Nominative, [true, 'семь'], [false, 'семь']],
            [Case.Genitive, [true, 'семи'], [false, 'семи']],
            [Case.Dative, [true, 'семи'], [false, 'семи']],
            [Case.Accusative, [true, 'семь'], [false, 'семь']],
            [Case.Instrumental, [true, 'семью'], [false, 'семью']],
            [Case.Prepositional, [true, 'семи'], [false, 'семи']]],
          [Gender.Feminine,
            [Case.Nominative, [true, 'семь'], [false, 'семь']],
            [Case.Genitive, [true, 'семи'], [false, 'семи']],
            [Case.Dative, [true, 'семи'], [false, 'семи']],
            [Case.Accusative, [true, 'семь'], [false, 'семь']],
            [Case.Instrumental, [true, 'семью'], [false, 'семью']],
            [Case.Prepositional, [true, 'семи'], [false, 'семи']]],
          [Gender.Neuter,
            [Case.Nominative, [true, 'семь'], [false, 'семь']],
            [Case.Genitive, [true, 'семи'], [false, 'семи']],
            [Case.Dative, [true, 'семи'], [false, 'семи']],
            [Case.Accusative, [true, 'семь'], [false, 'семь']],
            [Case.Instrumental, [true, 'семью'], [false, 'семью']],
            [Case.Prepositional, [true, 'семи'], [false, 'семи']]]],
        [8,
          [Gender.Masculine,
            [Case.Nominative, [true, 'восемь'], [false, 'восемь']],
            [Case.Genitive, [true, 'восьми'], [false, 'восьми']],
            [Case.Dative, [true, 'восьми'], [false, 'восьми']],
            [Case.Accusative, [true, 'восемь'], [false, 'восемь']],
            [Case.Instrumental,
              [true, 'восемью'],
              [false, 'восемью']],
            [Case.Prepositional, [true, 'восьми'], [false, 'восьми']]],
          [Gender.Feminine,
            [Case.Nominative, [true, 'восемь'], [false, 'восемь']],
            [Case.Genitive, [true, 'восьми'], [false, 'восьми']],
            [Case.Dative, [true, 'восьми'], [false, 'восьми']],
            [Case.Accusative, [true, 'восемь'], [false, 'восемь']],
            [Case.Instrumental,
              [true, 'восемью'],
              [false, 'восемью']],
            [Case.Prepositional, [true, 'восьми'], [false, 'восьми']]],
          [Gender.Neuter,
            [Case.Nominative, [true, 'восемь'], [false, 'восемь']],
            [Case.Genitive, [true, 'восьми'], [false, 'восьми']],
            [Case.Dative, [true, 'восьми'], [false, 'восьми']],
            [Case.Accusative, [true, 'восемь'], [false, 'восемь']],
            [Case.Instrumental,
              [true, 'восемью'],
              [false, 'восемью']],
            [Case.Prepositional, [true, 'восьми'], [false, 'восьми']]]],
        [9,
          [Gender.Masculine,
            [Case.Nominative, [true, 'девять'], [false, 'девять']],
            [Case.Genitive, [true, 'девяти'], [false, 'девяти']],
            [Case.Dative, [true, 'девяти'], [false, 'девяти']],
            [Case.Accusative, [true, 'девять'], [false, 'девять']],
            [Case.Instrumental,
              [true, 'девятью'],
              [false, 'девятью']],
            [Case.Prepositional, [true, 'девяти'], [false, 'девяти']]],
          [Gender.Feminine,
            [Case.Nominative, [true, 'девять'], [false, 'девять']],
            [Case.Genitive, [true, 'девяти'], [false, 'девяти']],
            [Case.Dative, [true, 'девяти'], [false, 'девяти']],
            [Case.Accusative, [true, 'девять'], [false, 'девять']],
            [Case.Instrumental,
              [true, 'девятью'],
              [false, 'девятью']],
            [Case.Prepositional, [true, 'девяти'], [false, 'девяти']]],
          [Gender.Neuter,
            [Case.Nominative, [true, 'девять'], [false, 'девять']],
            [Case.Genitive, [true, 'девяти'], [false, 'девяти']],
            [Case.Dative, [true, 'девяти'], [false, 'девяти']],
            [Case.Accusative, [true, 'девять'], [false, 'девять']],
            [Case.Instrumental,
              [true, 'девятью'],
              [false, 'девятью']],
            [Case.Prepositional, [true, 'девяти'], [false, 'девяти']]]],
        [10,
          [Gender.Masculine,
            [Case.Nominative, [true, 'десять'], [false, 'десять']],
            [Case.Genitive, [true, 'десяти'], [false, 'десяти']],
            [Case.Dative, [true, 'десяти'], [false, 'десяти']],
            [Case.Accusative, [true, 'десять'], [false, 'десять']],
            [Case.Instrumental,
              [true, 'десятью'],
              [false, 'десятью']],
            [Case.Prepositional, [true, 'десяти'], [false, 'десяти']]],
          [Gender.Feminine,
            [Case.Nominative, [true, 'десять'], [false, 'десять']],
            [Case.Genitive, [true, 'десяти'], [false, 'десяти']],
            [Case.Dative, [true, 'десяти'], [false, 'десяти']],
            [Case.Accusative, [true, 'десять'], [false, 'десять']],
            [Case.Instrumental,
              [true, 'десятью'],
              [false, 'десятью']],
            [Case.Prepositional, [true, 'десяти'], [false, 'десяти']]],
          [Gender.Neuter,
            [Case.Nominative, [true, 'десять'], [false, 'десять']],
            [Case.Genitive, [true, 'десяти'], [false, 'десяти']],
            [Case.Dative, [true, 'десяти'], [false, 'десяти']],
            [Case.Accusative, [true, 'десять'], [false, 'десять']],
            [Case.Instrumental,
              [true, 'десятью'],
              [false, 'десятью']],
            [Case.Prepositional, [true, 'десяти'], [false, 'десяти']]]],
        [11,
          [Gender.Masculine,
            [Case.Nominative,
              [true, 'одиннадцать'],
              [false, 'одиннадцать']],
            [Case.Genitive,
              [true, 'одиннадцати'],
              [false, 'одиннадцати']],
            [Case.Dative,
              [true, 'одиннадцати'],
              [false, 'одиннадцати']],
            [Case.Accusative,
              [true, 'одиннадцать'],
              [false, 'одиннадцать']],
            [Case.Instrumental,
              [true, 'одиннадцатью'],
              [false, 'одиннадцатью']],
            [Case.Prepositional,
              [true, 'одиннадцати'],
              [false, 'одиннадцати']]],
          [Gender.Feminine,
            [Case.Nominative,
              [true, 'одиннадцать'],
              [false, 'одиннадцать']],
            [Case.Genitive,
              [true, 'одиннадцати'],
              [false, 'одиннадцати']],
            [Case.Dative,
              [true, 'одиннадцати'],
              [false, 'одиннадцати']],
            [Case.Accusative,
              [true, 'одиннадцать'],
              [false, 'одиннадцать']],
            [Case.Instrumental,
              [true, 'одиннадцатью'],
              [false, 'одиннадцатью']],
            [Case.Prepositional,
              [true, 'одиннадцати'],
              [false, 'одиннадцати']]],
          [Gender.Neuter,
            [Case.Nominative,
              [true, 'одиннадцать'],
              [false, 'одиннадцать']],
            [Case.Genitive,
              [true, 'одиннадцати'],
              [false, 'одиннадцати']],
            [Case.Dative,
              [true, 'одиннадцати'],
              [false, 'одиннадцати']],
            [Case.Accusative,
              [true, 'одиннадцать'],
              [false, 'одиннадцать']],
            [Case.Instrumental,
              [true, 'одиннадцатью'],
              [false, 'одиннадцатью']],
            [Case.Prepositional,
              [true, 'одиннадцати'],
              [false, 'одиннадцати']]]],
        [12,
          [Gender.Masculine,
            [Case.Nominative,
              [true, 'двенадцать'],
              [false, 'двенадцать']],
            [Case.Genitive,
              [true, 'двенадцати'],
              [false, 'двенадцати']],
            [Case.Dative,
              [true, 'двенадцати'],
              [false, 'двенадцати']],
            [Case.Accusative,
              [true, 'двенадцать'],
              [false, 'двенадцать']],
            [Case.Instrumental,
              [true, 'двенадцатью'],
              [false, 'двенадцатью']],
            [Case.Prepositional,
              [true, 'двенадцати'],
              [false, 'двенадцати']]],
          [Gender.Feminine,
            [Case.Nominative,
              [true, 'двенадцать'],
              [false, 'двенадцать']],
            [Case.Genitive,
              [true, 'двенадцати'],
              [false, 'двенадцати']],
            [Case.Dative,
              [true, 'двенадцати'],
              [false, 'двенадцати']],
            [Case.Accusative,
              [true, 'двенадцать'],
              [false, 'двенадцать']],
            [Case.Instrumental,
              [true, 'двенадцатью'],
              [false, 'двенадцатью']],
            [Case.Prepositional,
              [true, 'двенадцати'],
              [false, 'двенадцати']]],
          [Gender.Neuter,
            [Case.Nominative,
              [true, 'двенадцать'],
              [false, 'двенадцать']],
            [Case.Genitive,
              [true, 'двенадцати'],
              [false, 'двенадцати']],
            [Case.Dative,
              [true, 'двенадцати'],
              [false, 'двенадцати']],
            [Case.Accusative,
              [true, 'двенадцать'],
              [false, 'двенадцать']],
            [Case.Instrumental,
              [true, 'двенадцатью'],
              [false, 'двенадцатью']],
            [Case.Prepositional,
              [true, 'двенадцати'],
              [false, 'двенадцати']]]],
        [13,
          [Gender.Masculine,
            [Case.Nominative,
              [true, 'тринадцать'],
              [false, 'тринадцать']],
            [Case.Genitive,
              [true, 'тринадцати'],
              [false, 'тринадцати']],
            [Case.Dative,
              [true, 'тринадцати'],
              [false, 'тринадцати']],
            [Case.Accusative,
              [true, 'тринадцать'],
              [false, 'тринадцать']],
            [Case.Instrumental,
              [true, 'тринадцатью'],
              [false, 'тринадцатью']],
            [Case.Prepositional,
              [true, 'тринадцати'],
              [false, 'тринадцати']]],
          [Gender.Feminine,
            [Case.Nominative,
              [true, 'тринадцать'],
              [false, 'тринадцать']],
            [Case.Genitive,
              [true, 'тринадцати'],
              [false, 'тринадцати']],
            [Case.Dative,
              [true, 'тринадцати'],
              [false, 'тринадцати']],
            [Case.Accusative,
              [true, 'тринадцать'],
              [false, 'тринадцать']],
            [Case.Instrumental,
              [true, 'тринадцатью'],
              [false, 'тринадцатью']],
            [Case.Prepositional,
              [true, 'тринадцати'],
              [false, 'тринадцати']]],
          [Gender.Neuter,
            [Case.Nominative,
              [true, 'тринадцать'],
              [false, 'тринадцать']],
            [Case.Genitive,
              [true, 'тринадцати'],
              [false, 'тринадцати']],
            [Case.Dative,
              [true, 'тринадцати'],
              [false, 'тринадцати']],
            [Case.Accusative,
              [true, 'тринадцать'],
              [false, 'тринадцать']],
            [Case.Instrumental,
              [true, 'тринадцатью'],
              [false, 'тринадцатью']],
            [Case.Prepositional,
              [true, 'тринадцати'],
              [false, 'тринадцати']]]],
        [14,
          [Gender.Masculine,
            [Case.Nominative,
              [true, 'четырнадцать'],
              [false, 'четырнадцать']],
            [Case.Genitive,
              [true, 'четырнадцати'],
              [false, 'четырнадцати']],
            [Case.Dative,
              [true, 'четырнадцати'],
              [false, 'четырнадцати']],
            [Case.Accusative,
              [true, 'четырнадцать'],
              [false, 'четырнадцать']],
            [Case.Instrumental,
              [true, 'четырнадцатью'],
              [false, 'четырнадцатью']],
            [Case.Prepositional,
              [true, 'четырнадцати'],
              [false, 'четырнадцати']]],
          [Gender.Feminine,
            [Case.Nominative,
              [true, 'четырнадцать'],
              [false, 'четырнадцать']],
            [Case.Genitive,
              [true, 'четырнадцати'],
              [false, 'четырнадцати']],
            [Case.Dative,
              [true, 'четырнадцати'],
              [false, 'четырнадцати']],
            [Case.Accusative,
              [true, 'четырнадцать'],
              [false, 'четырнадцать']],
            [Case.Instrumental,
              [true, 'четырнадцатью'],
              [false, 'четырнадцатью']],
            [Case.Prepositional,
              [true, 'четырнадцати'],
              [false, 'четырнадцати']]],
          [Gender.Neuter,
            [Case.Nominative,
              [true, 'четырнадцать'],
              [false, 'четырнадцать']],
            [Case.Genitive,
              [true, 'четырнадцати'],
              [false, 'четырнадцати']],
            [Case.Dative,
              [true, 'четырнадцати'],
              [false, 'четырнадцати']],
            [Case.Accusative,
              [true, 'четырнадцать'],
              [false, 'четырнадцать']],
            [Case.Instrumental,
              [true, 'четырнадцатью'],
              [false, 'четырнадцатью']],
            [Case.Prepositional,
              [true, 'четырнадцати'],
              [false, 'четырнадцати']]]],
        [15,
          [Gender.Masculine,
            [Case.Nominative,
              [true, 'пятнадцать'],
              [false, 'пятнадцать']],
            [Case.Genitive,
              [true, 'пятнадцати'],
              [false, 'пятнадцати']],
            [Case.Dative,
              [true, 'пятнадцати'],
              [false, 'пятнадцати']],
            [Case.Accusative,
              [true, 'пятнадцать'],
              [false, 'пятнадцать']],
            [Case.Instrumental,
              [true, 'пятнадцатью'],
              [false, 'пятнадцатью']],
            [Case.Prepositional,
              [true, 'пятнадцати'],
              [false, 'пятнадцати']]],
          [Gender.Feminine,
            [Case.Nominative,
              [true, 'пятнадцать'],
              [false, 'пятнадцать']],
            [Case.Genitive,
              [true, 'пятнадцати'],
              [false, 'пятнадцати']],
            [Case.Dative,
              [true, 'пятнадцати'],
              [false, 'пятнадцати']],
            [Case.Accusative,
              [true, 'пятнадцать'],
              [false, 'пятнадцать']],
            [Case.Instrumental,
              [true, 'пятнадцатью'],
              [false, 'пятнадцатью']],
            [Case.Prepositional,
              [true, 'пятнадцати'],
              [false, 'пятнадцати']]],
          [Gender.Neuter,
            [Case.Nominative,
              [true, 'пятнадцать'],
              [false, 'пятнадцать']],
            [Case.Genitive,
              [true, 'пятнадцати'],
              [false, 'пятнадцати']],
            [Case.Dative,
              [true, 'пятнадцати'],
              [false, 'пятнадцати']],
            [Case.Accusative,
              [true, 'пятнадцать'],
              [false, 'пятнадцать']],
            [Case.Instrumental,
              [true, 'пятнадцатью'],
              [false, 'пятнадцатью']],
            [Case.Prepositional,
              [true, 'пятнадцати'],
              [false, 'пятнадцати']]]],
        [16,
          [Gender.Masculine,
            [Case.Nominative,
              [true, 'шестнадцать'],
              [false, 'шестнадцать']],
            [Case.Genitive,
              [true, 'шестнадцати'],
              [false, 'шестнадцати']],
            [Case.Dative,
              [true, 'шестнадцати'],
              [false, 'шестнадцати']],
            [Case.Accusative,
              [true, 'шестнадцать'],
              [false, 'шестнадцать']],
            [Case.Instrumental,
              [true, 'шестнадцатью'],
              [false, 'шестнадцатью']],
            [Case.Prepositional,
              [true, 'шестнадцати'],
              [false, 'шестнадцати']]],
          [Gender.Feminine,
            [Case.Nominative,
              [true, 'шестнадцать'],
              [false, 'шестнадцать']],
            [Case.Genitive,
              [true, 'шестнадцати'],
              [false, 'шестнадцати']],
            [Case.Dative,
              [true, 'шестнадцати'],
              [false, 'шестнадцати']],
            [Case.Accusative,
              [true, 'шестнадцать'],
              [false, 'шестнадцать']],
            [Case.Instrumental,
              [true, 'шестнадцатью'],
              [false, 'шестнадцатью']],
            [Case.Prepositional,
              [true, 'шестнадцати'],
              [false, 'шестнадцати']]],
          [Gender.Neuter,
            [Case.Nominative,
              [true, 'шестнадцать'],
              [false, 'шестнадцать']],
            [Case.Genitive,
              [true, 'шестнадцати'],
              [false, 'шестнадцати']],
            [Case.Dative,
              [true, 'шестнадцати'],
              [false, 'шестнадцати']],
            [Case.Accusative,
              [true, 'шестнадцать'],
              [false, 'шестнадцать']],
            [Case.Instrumental,
              [true, 'шестнадцатью'],
              [false, 'шестнадцатью']],
            [Case.Prepositional,
              [true, 'шестнадцати'],
              [false, 'шестнадцати']]]],
        [17,
          [Gender.Masculine,
            [Case.Nominative,
              [true, 'семнадцать'],
              [false, 'семнадцать']],
            [Case.Genitive,
              [true, 'семнадцати'],
              [false, 'семнадцати']],
            [Case.Dative,
              [true, 'семнадцати'],
              [false, 'семнадцати']],
            [Case.Accusative,
              [true, 'семнадцать'],
              [false, 'семнадцать']],
            [Case.Instrumental,
              [true, 'семнадцатью'],
              [false, 'семнадцатью']],
            [Case.Prepositional,
              [true, 'семнадцати'],
              [false, 'семнадцати']]],
          [Gender.Feminine,
            [Case.Nominative,
              [true, 'семнадцать'],
              [false, 'семнадцать']],
            [Case.Genitive,
              [true, 'семнадцати'],
              [false, 'семнадцати']],
            [Case.Dative,
              [true, 'семнадцати'],
              [false, 'семнадцати']],
            [Case.Accusative,
              [true, 'семнадцать'],
              [false, 'семнадцать']],
            [Case.Instrumental,
              [true, 'семнадцатью'],
              [false, 'семнадцатью']],
            [Case.Prepositional,
              [true, 'семнадцати'],
              [false, 'семнадцати']]],
          [Gender.Neuter,
            [Case.Nominative,
              [true, 'семнадцать'],
              [false, 'семнадцать']],
            [Case.Genitive,
              [true, 'семнадцати'],
              [false, 'семнадцати']],
            [Case.Dative,
              [true, 'семнадцати'],
              [false, 'семнадцати']],
            [Case.Accusative,
              [true, 'семнадцать'],
              [false, 'семнадцать']],
            [Case.Instrumental,
              [true, 'семнадцатью'],
              [false, 'семнадцатью']],
            [Case.Prepositional,
              [true, 'семнадцати'],
              [false, 'семнадцати']]]],
        [18,
          [Gender.Masculine,
            [Case.Nominative,
              [true, 'восемнадцать'],
              [false, 'восемнадцать']],
            [Case.Genitive,
              [true, 'восемнадцати'],
              [false, 'восемнадцати']],
            [Case.Dative,
              [true, 'восемнадцати'],
              [false, 'восемнадцати']],
            [Case.Accusative,
              [true, 'восемнадцать'],
              [false, 'восемнадцать']],
            [Case.Instrumental,
              [true, 'восемнадцатью'],
              [false, 'восемнадцатью']],
            [Case.Prepositional,
              [true, 'восемнадцати'],
              [false, 'восемнадцати']]],
          [Gender.Feminine,
            [Case.Nominative,
              [true, 'восемнадцать'],
              [false, 'восемнадцать']],
            [Case.Genitive,
              [true, 'восемнадцати'],
              [false, 'восемнадцати']],
            [Case.Dative,
              [true, 'восемнадцати'],
              [false, 'восемнадцати']],
            [Case.Accusative,
              [true, 'восемнадцать'],
              [false, 'восемнадцать']],
            [Case.Instrumental,
              [true, 'восемнадцатью'],
              [false, 'восемнадцатью']],
            [Case.Prepositional,
              [true, 'восемнадцати'],
              [false, 'восемнадцати']]],
          [Gender.Neuter,
            [Case.Nominative,
              [true, 'восемнадцать'],
              [false, 'восемнадцать']],
            [Case.Genitive,
              [true, 'восемнадцати'],
              [false, 'восемнадцати']],
            [Case.Dative,
              [true, 'восемнадцати'],
              [false, 'восемнадцати']],
            [Case.Accusative,
              [true, 'восемнадцать'],
              [false, 'восемнадцать']],
            [Case.Instrumental,
              [true, 'восемнадцатью'],
              [false, 'восемнадцатью']],
            [Case.Prepositional,
              [true, 'восемнадцати'],
              [false, 'восемнадцати']]]],
        [19,
          [Gender.Masculine,
            [Case.Nominative,
              [true, 'девятнадцать'],
              [false, 'девятнадцать']],
            [Case.Genitive,
              [true, 'девятнадцати'],
              [false, 'девятнадцати']],
            [Case.Dative,
              [true, 'девятнадцати'],
              [false, 'девятнадцати']],
            [Case.Accusative,
              [true, 'девятнадцать'],
              [false, 'девятнадцать']],
            [Case.Instrumental,
              [true, 'девятнадцатью'],
              [false, 'девятнадцатью']],
            [Case.Prepositional,
              [true, 'девятнадцати'],
              [false, 'девятнадцати']]],
          [Gender.Feminine,
            [Case.Nominative,
              [true, 'девятнадцать'],
              [false, 'девятнадцать']],
            [Case.Genitive,
              [true, 'девятнадцати'],
              [false, 'девятнадцати']],
            [Case.Dative,
              [true, 'девятнадцати'],
              [false, 'девятнадцати']],
            [Case.Accusative,
              [true, 'девятнадцать'],
              [false, 'девятнадцать']],
            [Case.Instrumental,
              [true, 'девятнадцатью'],
              [false, 'девятнадцатью']],
            [Case.Prepositional,
              [true, 'девятнадцати'],
              [false, 'девятнадцати']]],
          [Gender.Neuter,
            [Case.Nominative,
              [true, 'девятнадцать'],
              [false, 'девятнадцать']],
            [Case.Genitive,
              [true, 'девятнадцати'],
              [false, 'девятнадцати']],
            [Case.Dative,
              [true, 'девятнадцати'],
              [false, 'девятнадцати']],
            [Case.Accusative,
              [true, 'девятнадцать'],
              [false, 'девятнадцать']],
            [Case.Instrumental,
              [true, 'девятнадцатью'],
              [false, 'девятнадцатью']],
            [Case.Prepositional,
              [true, 'девятнадцати'],
              [false, 'девятнадцати']]
          ]
        ]
      ],
      ['10, 20,.. 90 (tens)',
        [20, 'двадцать', 'двадцати', 'двадцати', 'двадцать', 'двадцатью', 'двадцати'],
        [30, 'тридцать', 'тридцати', 'тридцати', 'тридцать', 'тридцатью', 'тридцати'],
        [40, 'сорок', 'сорока', 'сорока', 'сорок', 'сорока', 'сорока'],
        [50, 'пятьдесят', 'пятидесяти', 'пятидесяти', 'пятьдесят', 'пятьюдесятью', 'пятидесяти'],
        [60, 'шестьдесят', 'шестидесяти', 'шестидесяти', 'шестьдесят', 'шестьюдесятью', 'шестидесяти'],
        [70, 'семьдесят', 'семидесяти', 'семидесяти', 'семьдесят', 'семьюдесятью', 'семидесяти'],
        [80, 'восемьдесят', 'восьмидесяти', 'восьмидесяти', 'восемьдесят', 'восемьюдесятью', 'восьмидесяти'],
        [90, 'девяносто', 'девяноста', 'девяноста', 'девяносто', 'девяноста', 'девяноста']
      ],
      ['100, 200,.. 900 (hundreds)',
        [100, 'сто', 'ста', 'ста', 'сто', 'ста', 'ста'],
        [200, 'двести', 'двухсот', 'двумстам', 'двести', 'двумястами', 'двухстах'],
        [300, 'триста', 'трёхсот', 'трёмстам', 'триста', 'тремястами', 'трёхстах'],
        [400, 'четыреста', 'четырёхсот', 'четырёмстам', 'четыреста', 'четырьмястами', 'четырёхстах'],
        [500, 'пятьсот', 'пятисот', 'пятистам', 'пятьсот', 'пятьюстами', 'пятистах'],
        [600, 'шестьсот', 'шестисот', 'шестистам', 'шестьсот', 'шестьюстами', 'шестистах'],
        [700, 'семьсот', 'семисот', 'семистам', 'семьсот', 'семьюстами', 'семистах'],
        [800, 'восемьсот', 'восьмисот', 'восьмистам', 'восемьсот', 'восемьюстами', 'восьмистах'],
        [900, 'девятьсот', 'девятисот', 'девятистам', 'девятьсот', 'девятьюстами', 'девятистах']
      ],
      ['1000',
        [1000, 'одна тысяча', 'одной тысячи', 'одной тысяче', 'одну тысячу', 'одной тысячей', 'одной тысяче'],
        [2000, 'две тысячи', 'двух тысяч', 'двум тысячам', 'две тысячи', 'двумя тысячами', 'двух тысячах'],
        [5000, 'пять тысяч', 'пяти тысяч', 'пяти тысячам', 'пять тысяч', 'пятью тысячами', 'пяти тысячах']
      ],
      ['1000²',
        [1000000,
          'один миллион',
          'одного миллиона',
          'одному миллиону',
          'один миллион',
          'одним миллионом',
          'одном миллионе'
        ],
        [2000000,
          'два миллиона',
          'двух миллионов',
          'двум миллионам',
          'два миллиона',
          'двумя миллионами',
          'двух миллионах'
        ],
        [5000000,
          'пять миллионов',
          'пяти миллионов',
          'пяти миллионам',
          'пять миллионов',
          'пятью миллионами',
          'пяти миллионах'
        ]
      ],
      ['1000³',
        [1000000000,
          'один миллиард',
          'одного миллиарда',
          'одному миллиарду',
          'один миллиард',
          'одним миллиардом',
          'одном миллиарде'
        ],
        [2000000000,
          'два миллиарда',
          'двух миллиардов',
          'двум миллиардам',
          'два миллиарда',
          'двумя миллиардами',
          'двух миллиардах'
        ],
        [5000000000,
          'пять миллиардов',
          'пяти миллиардов',
          'пяти миллиардам',
          'пять миллиардов',
          'пятью миллиардами',
          'пяти миллиардах'
        ]
      ],
      ['1000⁴',
        [1000000000000,
          'один триллион',
          'одного триллиона',
          'одному триллиону',
          'один триллион',
          'одним триллионом',
          'одном триллионе'
        ],
        [2000000000000,
          'два триллиона',
          'двух триллионов',
          'двум триллионам',
          'два триллиона',
          'двумя триллионами',
          'двух триллионах'
        ],
        [5000000000000,
          'пять триллионов',
          'пяти триллионов',
          'пяти триллионам',
          'пять триллионов',
          'пятью триллионами',
          'пяти триллионах'
        ]
      ],
      ['misc',
        [5122981121,
          [Gender.Masculine,
            [Case.Nominative,
              [true, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одна тысяча сто двадцать один'],
              [false, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одна тысяча сто двадцать один']
            ],
            [Case.Genitive,
              [true, 'пяти миллиардов ста двадцати двух миллионов девятисот восьмидесяти одной тысячи ста двадцати одного'],
              [false, 'пяти миллиардов ста двадцати двух миллионов девятисот восьмидесяти одной тысячи ста двадцати одного']
            ],
            [Case.Dative,
              [true, 'пяти миллиардам ста двадцати двум миллионам девятистам восьмидесяти одной тысяче ста двадцати одному'],
              [false, 'пяти миллиардам ста двадцати двум миллионам девятистам восьмидесяти одной тысяче ста двадцати одному']
            ],
            [Case.Accusative,
              [true, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одну тысячу сто двадцать одного'],
              [false, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одну тысячу сто двадцать один']
            ],
            [Case.Instrumental,
              [true, 'пятью миллиардами ста двадцатью двумя миллионами девятьюстами восемьюдесятью одной тысячей ста двадцатью одним'],
              [false, 'пятью миллиардами ста двадцатью двумя миллионами девятьюстами восемьюдесятью одной тысячей ста двадцатью одним']
            ],
            [Case.Prepositional,
              [true, 'пяти миллиардах ста двадцати двух миллионах девятистах восьмидесяти одной тысяче ста двадцати одном'],
              [false, 'пяти миллиардах ста двадцати двух миллионах девятистах восьмидесяти одной тысяче ста двадцати одном']
            ]
          ],
          [Gender.Feminine,
            [Case.Nominative,
              [true, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одна тысяча сто двадцать одна'],
              [false, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одна тысяча сто двадцать одна']
            ],
            [Case.Genitive,
              [true, 'пяти миллиардов ста двадцати двух миллионов девятисот восьмидесяти одной тысячи ста двадцати одной'],
              [false, 'пяти миллиардов ста двадцати двух миллионов девятисот восьмидесяти одной тысячи ста двадцати одной']
            ],
            [Case.Dative,
              [true, 'пяти миллиардам ста двадцати двум миллионам девятистам восьмидесяти одной тысяче ста двадцати одной'],
              [false, 'пяти миллиардам ста двадцати двум миллионам девятистам восьмидесяти одной тысяче ста двадцати одной']
            ],
            [Case.Accusative,
              [true, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одну тысячу сто двадцать одну'],
              [false, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одну тысячу сто двадцать одну']
            ],
            [Case.Instrumental,
              [true, 'пятью миллиардами ста двадцатью двумя миллионами девятьюстами восемьюдесятью одной тысячей ста двадцатью одной'],
              [false, 'пятью миллиардами ста двадцатью двумя миллионами девятьюстами восемьюдесятью одной тысячей ста двадцатью одной']
            ],
            [Case.Prepositional,
              [true, 'пяти миллиардах ста двадцати двух миллионах девятистах восьмидесяти одной тысяче ста двадцати одной'],
              [false, 'пяти миллиардах ста двадцати двух миллионах девятистах восьмидесяти одной тысяче ста двадцати одной']
            ]
          ],
          [Gender.Neuter,
            [Case.Nominative,
              [true, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одна тысяча сто двадцать одно'],
              [false, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одна тысяча сто двадцать одно']
            ],
            [Case.Genitive,
              [true, 'пяти миллиардов ста двадцати двух миллионов девятисот восьмидесяти одной тысячи ста двадцати одного'],
              [false, 'пяти миллиардов ста двадцати двух миллионов девятисот восьмидесяти одной тысячи ста двадцати одного']
            ],
            [Case.Dative,
              [true, 'пяти миллиардам ста двадцати двум миллионам девятистам восьмидесяти одной тысяче ста двадцати одному'],
              [false, 'пяти миллиардам ста двадцати двум миллионам девятистам восьмидесяти одной тысяче ста двадцати одному']
            ],
            [Case.Accusative,
              [true, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одну тысячу сто двадцать одно'],
              [false, 'пять миллиардов сто двадцать два миллиона девятьсот восемьдесят одну тысячу сто двадцать одно']
            ],
            [Case.Instrumental,
              [true, 'пятью миллиардами ста двадцатью двумя миллионами девятьюстами восемьюдесятью одной тысячей ста двадцатью одним'],
              [false, 'пятью миллиардами ста двадцатью двумя миллионами девятьюстами восемьюдесятью одной тысячей ста двадцатью одним']
            ],
            [Case.Prepositional,
              [true, 'пяти миллиардах ста двадцати двух миллионах девятистах восьмидесяти одной тысяче ста двадцати одном'],
              [false, 'пяти миллиардах ста двадцати двух миллионах девятистах восьмидесяти одной тысяче ста двадцати одном']
            ]
          ]
        ]
      ]
    ]
  ;

  const genders = Object.values(Gender).filter((gender): gender is Gender => typeof gender === 'number');
  const cases = Object.values(Case).filter((kase): kase is Case => typeof kase === 'number');

  testCases.forEach(([title, ...rest]) => {
    describe(title, () => {
      rest.forEach(([argNumber, ...rest]) => {
        if (isComplex(rest)) {
          rest.forEach(([argGender, ...rest]) => {
            rest.forEach(([argCase, ...rest]) => {
              rest.forEach(([argAnimate, expected]) => {
                it(`numeralize(${argNumber}, Gender.${Gender[argGender]}, Case.${Case[argCase]}, ${argAnimate}) → ${expected}`, () => {
                  assert.strictEqual(
                    numeralize(
                      argNumber,
                      argGender,
                      argCase,
                      argAnimate
                    ),
                    expected
                  );
                });
              });
            });
          });
        } else {
          genders.forEach((argGender) => {
            cases.forEach((argCase, i) => {
              [true, false].forEach((argAnimate) => {
                const expected = rest[i];
                it(`numeralize(${argNumber}, Gender.${Gender[argGender]}, Case.${Case[argCase]}, ${argAnimate}) → ${expected}`, () => {
                  assert.strictEqual(
                    numeralize(
                      argNumber,
                      argGender,
                      argCase,
                      argAnimate
                    ),
                    expected
                  );
                });
              })
            })
          })
        }
      });
    });
  });
});
